name: Deploy Laravel App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run Migrations
        run: php artisan migrate --force
      - name: Clear and Cache Config
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      - name: Restart Queue
        run: php artisan queue:restart
      - name: Kirim Notifikasi ke Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Workflow pada STB telah selesai dijalankan."
        if: always():contentReference[oaicite:46]{index=46}

